### ISSUE TITLE
Unsure of how to install (Not all that good at modding)

### ISSUE THREAD

**Issue by TheArchivisst** [AndyLobjois/BRC-MeshRemix#3]
I'm unsure if I'm following the instructions for installation that are posted on the Thunderstore page. Screenshots attached below:

![image](https://github.com/AndyLobjois/BRC-DripRemix/assets/81943300/dd964173-06c5-4cad-aef5-fd5b82230304)
![image](https://github.com/AndyLobjois/BRC-DripRemix/assets/81943300/bfa96acf-4796-401f-aa21-a4cee62280a8)
![image](https://github.com/AndyLobjois/BRC-DripRemix/assets/81943300/1eda5a55-a31b-4b42-817a-ce3bad3c7847)

**Comment by AndyLobjois** [comment]
Looks alright to me, do you have Gears folders too ?
I fixed a bug with the recent update [DripRemix 1.0.1](https://lethal-league-blaze.thunderstore.io/c/bomb-rush-cyberfunk/p/AndyLobjois/DripRemix/). When you don't create any gears folders, the script will try to find them anyway and throw an error.
Perhaps it's your case ?

**Comment by TheArchivisst** [comment]
I have the gears folders but there's no files inside of them. Should there be?

**Comment by TheArchivisst** [comment]
Actually I just checked and the issue was solved by the update. Thank you!

**Comment by AndyLobjois** [comment]
Good to hear !
