### ISSUE TITLE
Mod suddenly stopped working

### ISSUE THREAD

**Issue by Rakkult** [AndyLobjois/BRC-MeshRemix#4]
I changed the keybinds to some unused keys to swap between skins and models, everything was working normally, but then the mod stopped working, I can still hit the reload key and it works, but I can't change skins or models anymore, I tried everything but couldn't make it work again, I changed keybinds to default, checked if any mod was incompatible, and did a fresh install but nothing seems to work, it loads correctly on bepinex console tho

**Comment by AndyLobjois** [comment]
Yo, did you get this bug while using Felix ? Several peoples report me that Felix doesn't works for some reason, and I have to finish the game for testing that (haha). If it's the case, don't use him for now. I'll keep you updated on fix error, sorry for the inconvenience.

**Comment by AndyLobjois** [comment]
Yo again, I updated DripRemix and fix Felix missing reference. Hopes it will fix your issue !

**Comment by Rakkult** [comment]
Thank you!! I did get the bug while using felix, i didn’t realize i was only trying with him, now it works 👍

**Comment by AndyLobjois** [comment]
Very good !
