### ISSUE TITLE
Only working keybind is Reload

### ISSUE THREAD

**Issue by WallyCat** [AndyLobjois/BRC-MeshRemix#5]
Trying to use any other keybind to switch the character/spray can color/ect doesn't work, the only one that works for me is the reload key, no matter which keys I bind any of them to.

**Comment by AndyLobjois** [comment]
Yo ! Sorry for the big delay, I was fixing several issues and I think your issue is one of them !
Can you update to 1.0.3 pls ? https://lethal-league-blaze.thunderstore.io/c/bomb-rush-cyberfunk/p/AndyLobjois/DripRemix/

Keep me updated if it fix your issue :)

**Comment by WallyCat** [comment]
Hey! It's all good, I appreciate the fix. It's all working as intended now!

**Comment by AndyLobjois** [comment]
Glad to hear !
