### ISSUE TITLE
Mod No Longer Seems To Load After Most Recent Update

### ISSUE THREAD

**Issue by TheArchivisst** [AndyLobjois/BRC-MeshRemix#6]
After the most recent update, when the game starts up the mod doesn't load. 

Copy of my dev console, if that helps:

> [Message:   BepInEx] BepInEx 5.4.21.0 - Bomb Rush Cyberfunk (8/19/2023 5:34:04 PM)
[Info   :   BepInEx] Running under Unity v2021.3.27.13254651
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
Setting breakpad minidump AppID = 1353230
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198343072690 [API loaded no]
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 6 plugins to load
[Info   :   BepInEx] Loading [BombRushDiscord 1.2.0]
[Info   :BombRushDiscord] PluginName: BombRushDiscord, VersionString: 1.2.0 is loading...
[Info   :BombRushDiscord] PluginName: BombRushDiscord, VersionString: 1.2.0 is loaded.
[Info   :   BepInEx] Loading [GimmeMyBoost 1.0.0]
[Info   :GimmeMyBoost] GimmeMyBoost has been loaded!
[Info   :   BepInEx] Loading [DripRemix 1.0.4]
[Info   :   BepInEx] Loading [BRCModdingLib 0.2.0]
[Info   :BRCModdingLib] Hello, world!
[Info   :   BepInEx] Loading [Bomb Rush Radio! 1.3.2.0]
[Info   :Bomb Rush Radio!] [BRR] Loading songs...
[Info   :Bomb Rush Radio!] [BRR] Searching directory C:/Program Files (x86)/Steam/steamapps/common/BombRushCyberfunk/Bomb Rush Cyberfunk_Data/StreamingAssets/Mods/BombRushRadio/Songs\Beck
[Info   :Bomb Rush Radio!] [BRR] Searching directory C:/Program Files (x86)/Steam/steamapps/common/BombRushCyberfunk/Bomb Rush Cyberfunk_Data/StreamingAssets/Mods/BombRushRadio/Songs\Blackstreet
[Info   :Bomb Rush Radio!] [BRR] Searching directory C:/Program Files (x86)/Steam/steamapps/common/BombRushCyberfunk/Bomb Rush Cyberfunk_Data/StreamingAssets/Mods/BombRushRadio/Songs\ICP
[Info   :Bomb Rush Radio!] [BRR] Searching directory C:/Program Files (x86)/Steam/steamapps/common/BombRushCyberfunk/Bomb Rush Cyberfunk_Data/StreamingAssets/Mods/BombRushRadio/Songs\MF Doom
[Info   :Bomb Rush Radio!] [BRR] Searching directory C:/Program Files (x86)/Steam/steamapps/common/BombRushCyberfunk/Bomb Rush Cyberfunk_Data/StreamingAssets/Mods/BombRushRadio/Songs\Ween
[Info   :Bomb Rush Radio!] [BRR] Searching directory C:/Program Files (x86)/Steam/steamapps/common/BombRushCyberfunk/Bomb Rush Cyberfunk_Data/StreamingAssets/Mods/BombRushRadio/Songs\Wyclef Jean
[Info   :Bomb Rush Radio!] [BRR] Patched...
[Info   :   BepInEx] Loading [SlopCrew 1.4.6]
[Message:BombRushDiscord] SlopCrew API registered.
[Message:   BepInEx] Chainloader startup complete
[Info   :Bomb Rush Radio!] [BRR] Loaded Loser by Beck (1/8)
[Info   :Bomb Rush Radio!] [BRR] Loaded My Axe by Insane Clown Posse (2/8)
[Info   :Bomb Rush Radio!] [BRR] Loaded Rapp Snitch Knishes (feat. Mr. Fantastik) by MF Doom (3/8)
[Info   :Bomb Rush Radio!] [BRR] Loaded All Outta Ale by MF Doom (4/8)
[Info   :Bomb Rush Radio!] [BRR] Loaded Imma Kill U by Insane Clown Posse (5/8)
[Info   :Bomb Rush Radio!] [BRR] Loaded No Diggity by Blackstreet (6/8)
[Info   :Bomb Rush Radio!] [BRR] Loaded We Trying to Stay Alive (feat. John Forté & Pras) by Wyclef Jean (7/8)
[Info   :Bomb Rush Radio!] [BRR] Loaded Monique The Freak by Ween (8/8)
[Info   :BombRushDiscord] The start event here actually fires.
[Info   :Bomb Rush Radio!] [BRR] Bomb Rush Radio has been loaded!
[Info   : Unity Log] Core.Awake(): Version: 1.0.19866
[Info   : Unity Log] Core.Awake(): Initial quality setting: Ultra
[Info   : Unity Log] Core.Awake(): Initial resolution: 1920 x 1080 @ 144Hz
[Info   : Unity Log] Core.Awake(): Initial language: English
[Info   : Unity Log] Core.Awake(): Platform data loaded: WindowsPlatformData

**Comment by AndyLobjois** [comment]
Yo, it is → `[Info : BepInEx] Loading [DripRemix 1.0.4]`
I've changed the design and now the load is done once in game.
Also, make sure to update your examples files.
