### ISSUE TITLE
mod not working...

### ISSUE THREAD

**Issue by JooZehh** [AndyLobjois/BRC-MeshRemix#7]
I seem to be going through every hotkey and can't figure out why the models are not changing. The mod is updated to the latest version along with the examples yet it doesn't not work. I tried seeing if there's conflict with quick style swap but after uninstalling that, it still does not work. How do I fix this issue?

**Comment by JooZehh** [comment]
ok no mod works but it does not work with custom_api characters, is there a way to fix this?

**Comment by AndyLobjois** [comment]
Last Update should works with Custom Characters, upgrade to DripRemix 1.0.8 please :D
