### ISSUE TITLE
Custom Characters added do not have indexes

### ISSUE THREAD

**Issue by KipalaB** [AndyLobjois/BRC-MeshRemix#8]
When custom characters are added via CrewBoom or BRCCCCLoader that have their own character, not replacing a default character it throws an error stating they can't find them due to lack of index. Is there a way to add new indexes to get custom separate characters to work with DripRemix?

Otherwise works with default characters.

When loading a custom character (Cherry for example)

> [Error  : Unity Log] KeyNotFoundException: The given key '28' was not present in the dictionary.
> Stack trace:
> System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <1c8569827291471e9db0dcd976e97952>:0)
> DripRemix.Handlers.DripHandler.get_INDEX_MESH () (at <1fc74cbb9cf243afaaa75b0a2fe4ffa0>:0)
> DripRemix.Handlers.DripHandler.LoadDetails (System.String typeName, System.String characterName) (at <1fc74cbb9cf243afaaa75b0a2fe4ffa0>:0)
> DripRemix.Handlers.GearHandler.GetAssets () (at <1fc74cbb9cf243afaaa75b0a2fe4ffa0>:0)
> DripRemix.Main.ReloadAssets () (at <1fc74cbb9cf243afaaa75b0a2fe4ffa0>:0)
> DripRemix.Main.LateUpdate () (at <1fc74cbb9cf243afaaa75b0a2fe4ffa0>:0)

When changing gear

> [Error  : Unity Log] KeyNotFoundException: The given key '28' was not present in the dictionary.
> Stack trace:
> System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <1c8569827291471e9db0dcd976e97952>:0)
> DripRemix.Handlers.DripHandler.get_INDEX_TEXTURE () (at <1fc74cbb9cf243afaaa75b0a2fe4ffa0>:0)
> DripRemix.Handlers.GearHandler.SetTexture (System.Int32 indexMod) (at <1fc74cbb9cf243afaaa75b0a2fe4ffa0>:0)
> DripRemix.Main.SetTexture (DripRemix.Main+Check check, System.Int32 add) (at <1fc74cbb9cf243afaaa75b0a2fe4ffa0>:0)
> DripRemix.Main.CheckInput (UnityEngine.KeyCode key, DripRemix.Main+Check check) (at <1fc74cbb9cf243afaaa75b0a2fe4ffa0>:0)
> DripRemix.Main.Update () (at <1fc74cbb9cf243afaaa75b0a2fe4ffa0>:0)

**Comment by AndyLobjois** [comment]
Last update should works with Custom Characters, try DripRemix 1.0.8 please
