### ISSUE TITLE
Missing/Wrong info.txt

### ISSUE THREAD

**Issue by EzeroBlue** [AndyLobjois/BRC-MeshRemix#9]
I'm not sure why but its telling me that the info.txt is wrong but the one for Incline is correct?
I'm confused on why it thinks its wrong or missing

![image](https://github.com/AndyLobjois/BRC-DripRemix/assets/149824620/96972368-b5e1-493f-b548-99ff7322de78)

**Comment by AndyLobjois** [comment]
This error shows up if DripRemix can't read the info.txt file of the category : if it doesn't exist or if there is an error inside.
Please check the file and see if you missed something.

This the BMX info.txt for example :
```
name=Default BMX
author=Team Reptile
```

**Comment by EzeroBlue** [comment]
I was able to fix it it doesn't show up as an error anymore, but now it doesn't allow me to change models, Like from the Balance Wii Board to the Default Skateboard

**Comment by AndyLobjois** [comment]
Default assets have to be added in the folders (from my examples.zip).
Some people don't want to cycle with the default gears, hence the possibility to not have them at all.

But from your screenshot, default gears are there. Are you sure to use the correct shortcuts and/or your keyboard allow the key combinations ?

```
HOW TO USE

Reload : F5 (Useful for quick editing !)

    Character : Hold C ...
    Gears : Hold G ...
    Phone : Hold P ...
    Spraycan : Hold E ...
        ... and Press PageUp/PageDown for scrolling through your Skins !
        ... or Press Home/End for scrolling through your Models !

You can edit the bindings from the config file inside BepInEx/config
```

**Comment by EzeroBlue** [comment]
The shortcuts are working fine however when it comes to switching the models it seems to have issues
![image](https://github.com/AndyLobjois/BRC-DripRemix/assets/149824620/ab5867eb-242a-41b9-9c1d-1de27a991d55)

I'm sorry if I can't send the video since the size is bigger than 10MBs

**Comment by AndyLobjois** [comment]
I have no idea where the issue is then.
Also I want to rectify myself from previous message : You can't "cycle" through gears but only scrolls, which means if you are in the end of the list, you have to press PageUp or Home for getting back to the previous model/texture gears.

I'm in the Team Reptile Hideout Discord if you want screenshare with me (ping me with @AndyHellgrim)

Edit: After a screenshare, there is no issue, just a misunderstanding about home/end for scrolling models
